# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blogs
    url: blog/
    weight: 20
  - name: People
    url: people/
    weight: 20
  # - name: Uses
  #   url: uses/
  #   weight: 30
