# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blogs
    url: blog/
    weight: 20
  - name: People
    url: people/
    weight: 30
  - name: Reading
    url: reading/
    weight: 40
  - name: Data
    url: data/
    weight: 50
  # - name: Uses
  #   url: uses/
  #   weight: 30
